[package]
name = "net-tac-toe"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tic-tac-toe = { path = "../tic-tac-toe" }
clap = { version = "*", features = ["derive"] }
promptly = "0.3.1"
