name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            package: crates/net-tac-toe
            archive: zip
          - target: x86_64-unknown-linux-musl
            package: crates/net-tac-toe
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            package: crates/net-tac-toe
            archive: zip
            
          - target: x86_64-pc-windows-gnu
            package: crates/tic-tac-toe
            archive: zip
          - target: x86_64-unknown-linux-musl
            package: crates/tic-tac-toe
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            package: crates/tic-tac-toe
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ${{ matrix.package }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
